# Generated by Django 3.2 on 2022-07-15 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=60)),
                ('etatEnc', models.CharField(max_length=30)),
                ('etat', models.JSONField(blank=True, null=True)),
                ('derniereFacture', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
