# Generated by Django 4.0.5 on 2022-07-03 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 3, 18, 28, 51, 653055, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
