# Generated by Django 4.0.5 on 2022-07-02 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Steg',
            new_name='Facture',
        ),
    ]
