# Generated by Django 3.2.1 on 2022-07-17 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(blank=True, max_length=100, null=True)),
                ('lit', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('datePaie', models.CharField(blank=True, max_length=100, null=True)),
                ('dateNais', models.CharField(blank=True, max_length=100, null=True)),
                ('etatAffiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('cin', models.CharField(blank=True, max_length=100, null=True)),
                ('libModeRecrut', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assuree',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cin', models.CharField(blank=True, max_length=100, null=True)),
                ('dateAf', models.CharField(blank=True, max_length=100, null=True)),
                ('dateFinContrat', models.CharField(blank=True, max_length=100, null=True)),
                ('dateNaissance', models.CharField(blank=True, max_length=100, null=True)),
                ('etatAffiliation', models.CharField(blank=True, max_length=100, null=True)),
                ('libCodePos', models.CharField(blank=True, max_length=100, null=True)),
                ('libModeRecrut', models.CharField(blank=True, max_length=100, null=True)),
                ('matricule', models.CharField(blank=True, max_length=100, null=True)),
                ('modRecru', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('sexe', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
