# Generated by Django 3.2.1 on 2022-07-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactionsonede',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('coderetour', models.CharField(blank=True, max_length=60, null=True)),
                ('reftrs', models.CharField(blank=True, max_length=80, null=True)),
                ('montant', models.CharField(blank=True, max_length=280, null=True)),
                ('card', models.CharField(blank=True, max_length=280, null=True)),
                ('partner', models.CharField(blank=True, max_length=280, null=True)),
                ('date_trs', models.CharField(blank=True, max_length=80, null=True)),
                ('autorisation', models.CharField(blank=True, max_length=80, null=True)),
                ('status_trs', models.CharField(blank=True, max_length=20, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
