# Generated by Django 3.2.1 on 2022-07-17 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cnammatriculecaisse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codeBureau', models.CharField(blank=True, max_length=100, null=True)),
                ('dateDossier', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=100, null=True)),
                ('caisse', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroDossier', models.CharField(blank=True, max_length=100, null=True)),
                ('dateSoins', models.CharField(blank=True, max_length=100, null=True)),
                ('caisseAssure', models.CharField(blank=True, max_length=100, null=True)),
                ('identifiantUniqueAssure', models.CharField(blank=True, max_length=100, null=True)),
                ('matriculeAssure', models.CharField(blank=True, max_length=100, null=True)),
                ('qualiteBeneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('rangBeneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('nomBeneficiaire', models.CharField(blank=True, max_length=100, null=True)),
                ('regime', models.CharField(blank=True, max_length=100, null=True)),
                ('etatDossier', models.CharField(blank=True, max_length=100, null=True)),
                ('decisionAdministrative', models.CharField(blank=True, max_length=100, null=True)),
                ('totalDepense', models.CharField(blank=True, max_length=100, null=True)),
                ('totalRembourse', models.CharField(blank=True, max_length=100, null=True)),
                ('referenceVir', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cnamdetailsoin',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codeBureau', models.CharField(blank=True, max_length=100, null=True)),
                ('dateDossier', models.CharField(blank=True, max_length=100, null=True)),
                ('numeroDossier', models.CharField(blank=True, max_length=100, null=True)),
                ('refernceBulletin', models.CharField(blank=True, max_length=100, null=True)),
                ('typeActe', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('dateActe', models.CharField(blank=True, max_length=100, null=True)),
                ('decision', models.CharField(blank=True, max_length=100, null=True)),
                ('montantDepense', models.CharField(blank=True, max_length=100, null=True)),
                ('montantReel', models.CharField(blank=True, max_length=100, null=True)),
                ('montantRembourse', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
