# Generated by Django 3.2.1 on 2022-07-20 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturesonede',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billerAuthId', models.CharField(blank=True, max_length=60, null=True)),
                ('billerMf', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceRef', models.CharField(blank=True, max_length=60, null=True)),
                ('ttnRef', models.CharField(blank=True, max_length=60, null=True)),
                ('contractNumber', models.CharField(blank=True, max_length=60, null=True)),
                ('clientCode', models.CharField(blank=True, max_length=60, null=True)),
                ('clientCin', models.CharField(blank=True, max_length=60, null=True)),
                ('clientPassport', models.CharField(blank=True, max_length=60, null=True)),
                ('clientCs', models.CharField(blank=True, max_length=60, null=True)),
                ('clientMf', models.CharField(blank=True, max_length=60, null=True)),
                ('clientName', models.CharField(blank=True, max_length=60, null=True)),
                ('clientLastname', models.CharField(blank=True, max_length=60, null=True)),
                ('clientRs', models.CharField(blank=True, max_length=60, null=True)),
                ('clientPhones', models.CharField(blank=True, max_length=60, null=True)),
                ('clientEmails', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceTaxAmount', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceOriginalAmount', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceAmount', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceDate', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceExpiryDate', models.CharField(blank=True, max_length=60, null=True)),
                ('invoiceAttachments', models.CharField(blank=True, max_length=60, null=True)),
                ('paymentStatus', models.CharField(blank=True, max_length=60, null=True)),
                ('invoicePreiod', models.JSONField(blank=True, null=True)),
                ('invoiceDetails', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
